[package]
name = "eduos-rs"
version = "0.1.0"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"	# Low-level functions like memcpy.
raw-cpuid = "3.0.0"
cpuio = "0.2.0"
spin = "0.4.6"
alloc_kernel = { path = "alloc_kernel" }

[dependencies.lazy_static]
version = "0.2"
features = ["spin_no_std"]

[dependencies.x86]
version = "0.8"
default-features = false # do not include the default features

# The development profile, used for `cargo build`.
[profile.dev]
opt-level = 0      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-C debuginfo`
                   # a value of `true` is equivalent to `2`
rpath = false      # controls whether the compiler passes `-C rpath`
lto = false        # controls `-C lto` for binaries and staticlibs
debug-assertions = true # controls whether debug assertions are enabled
codegen-units = 1  # controls whether the compiler passes `-C codegen-units`
                   # `codegen-units` is ignored when `lto = true`

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
